CREATE TABLE IF NOT EXISTS projects (id UUID PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS campaigns (id UUID PRIMARY KEY, project_id UUID NOT NULL REFERENCES projects(id), objective TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS approvals (id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id UUID NOT NULL, status TEXT NOT NULL, requested_by TEXT NOT NULL, decided_by TEXT, reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), decided_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS routing_decisions (id UUID PRIMARY KEY, request_id TEXT NOT NULL, task_class TEXT NOT NULL, policy_mode TEXT NOT NULL, winner_model_id TEXT NOT NULL, payload JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_offer_snapshots (id UUID PRIMARY KEY, product_id TEXT NOT NULL, offer_id TEXT NOT NULL, seller_id TEXT NOT NULL, captured_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS publications (id UUID PRIMARY KEY, master_content_id UUID NOT NULL, workspace_id TEXT NOT NULL, platform TEXT NOT NULL, status TEXT NOT NULL, payload JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), published_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS outbox_events (id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL, event_type TEXT NOT NULL, payload JSONB NOT NULL, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), published_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON outbox_events (occurred_at) WHERE published_at IS NULL;
CREATE TABLE IF NOT EXISTS authorization_audit_events (id UUID PRIMARY KEY, actor_id TEXT NOT NULL, resource TEXT NOT NULL, action TEXT NOT NULL, permission_id TEXT, required_scope TEXT, risk_class TEXT, decision TEXT NOT NULL, reason TEXT NOT NULL, matched_rule_id TEXT, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now());
